name: book
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.9+10

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  flutter_svg: ^2.0.4
  google_mobile_ads: ^4.0.0
  sqflite: ^2.0.2+1
  path_provider: ^2.0.9
  flutter_screen_wake: ^1.0.2
  share_plus: ^6.3.1
  launch_review: ^3.0.1
  shared_preferences: ^2.0.13
  flutter_material_color_picker: ^1.1.0+2
  country_code_picker: ^3.0.0
  flutter_tts: ^3.3.3
  lottie: ^2.3.1
  url_launcher: ^6.0.9
  in_app_update: ^3.0.0
  carousel_slider: ^4.1.1
  facebook_audience_network: ^1.0.1
  flutter_localizations:
    sdk: flutter
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lorem_lpsum.db
    - assets/bookmark.db
    - assets/db_highlight.db
    - assets/images/
    - assets/Language/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 400
        - asset: fonts/Azad-Feni-Unicode Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 900
        - asset: fonts/Azad-Feni-Unicode Italic.ttf
          weight: 900
          style: italic
        - asset: fonts/Azad-Feni-Unicode Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 700
        - asset: fonts/Azad-Feni-Unicode Italic.ttf
          weight: 800
          style: italic
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 200
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 200
          style: italic
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 300
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 300
          style: italic
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 500
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 500
          style: italic
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 600
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 600
          style: italic
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 100
        - asset: fonts/Azad-Feni-Unicode.ttf
          weight: 100
          style: italic
fonts:
  - family: Solaiman
    fonts:
  - asset: fonts/SolaimanLipi.ttf